---
title: "Visualize Sprig Pruning"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualize Sprig Pruning}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(locater)
library(kalis)

# Load simulated haplotypes and recombination map
CacheHaplotypes(SmallHaps)
pars <- Parameters(CalcRho(diff(SmallMap)))


fwd <- MakeForwardTable(pars)
bck <- MakeBackwardTable(pars)
Forward(fwd,pars,50)
Backward(bck,pars,50)

cl <- Clades(fwd,bck,pars)
sp <- Sprigs(Neighbors(cl))

M1 <- CladeMat(cl,ploidy = 1)
M2 <- CladeMat(cl,ploidy = 1,sprigs.to.prune = sp)

perm <- fastcluster::hclust(stats::as.dist(-M1),method="average")$order
p1 <- lattice::levelplot(M1[perm,][,rev(perm)],
                         useRaster = TRUE,
                         col.regions = grDevices::colorRampPalette(RColorBrewer::brewer.pal(9,name = "BuPu"))(100),
                         yaxt = "n", xaxt = "n", xlab = "", ylab = "", xaxt = "n", at = seq(0,2,len=20))
p2 <- lattice::levelplot(M2[perm,][,rev(perm)],
                         useRaster = TRUE,
                         col.regions = grDevices::colorRampPalette(RColorBrewer::brewer.pal(9,name = "BuPu"))(100),
                         yaxt = "n", xaxt = "n", xlab = "", ylab = "", xaxt = "n", at = seq(0,2,len=20))

M1 <- CladeMat(cl,ploidy = 2)
M2 <- CladeMat(cl,ploidy = 2,sprigs.to.prune = sp)

perm <- fastcluster::hclust(stats::as.dist(-M1),method="average")$order
p3 <- lattice::levelplot(M1[perm,][,rev(perm)],
                         useRaster = TRUE,
                         col.regions = grDevices::colorRampPalette(RColorBrewer::brewer.pal(9,name = "BuPu"))(100),
                         yaxt = "n", xaxt = "n", xlab = "", ylab = "", xaxt = "n", at = seq(0,4,len=20))
p4 <- lattice::levelplot(M2[perm,][,rev(perm)],
                         useRaster = TRUE,
                         col.regions = grDevices::colorRampPalette(RColorBrewer::brewer.pal(9,name = "BuPu"))(100),
                         yaxt = "n", xaxt = "n", xlab = "", ylab = "", xaxt = "n", at = seq(0,4,len=20))

print(p1, split = c(1, 1, 2, 2), more = TRUE)
print(p2, split = c(2, 1, 2, 2), more = TRUE)
print(p3, split = c(1, 2, 2, 2), more = TRUE)
print(p4, split = c(2, 2, 2, 2), more = FALSE) 


```
